import React, { useState, useEffect } from 'react';
import { Loader2, CheckCircle, AlertCircle, X } from 'lucide-react';
import { Card, CardHeader, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Button } from '@/components/ui/button';
import { useAdminJobs, AdminJobExecution } from '@/hooks/useAdminJobs';
import { formatRelativeTime } from '@/lib/utils';
import { openChatPanelPrompt } from '@/lib/appNavigation';

interface LiveStatusCardProps {
  jobId: string;
  onCancel?: () => void;
  onViewDetails?: () => void;
}

export const LiveStatusCard: React.FC<LiveStatusCardProps> = ({
  jobId,
  onCancel,
  onViewDetails
}) => {
  const { activeJobs, cancelJob, retryJob } = useAdminJobs();
  const [job, setJob] = useState<AdminJobExecution | null>(null);

  useEffect(() => {
    const currentJob = activeJobs.find(j => j.id === jobId);
    setJob(currentJob || null);
  }, [activeJobs, jobId]);

  if (!job) {
    return null;
  }

  const getStatusIcon = () => {
    switch (job.status) {
      case 'running':
        return <Loader2 className="w-4 h-4 animate-spin text-blue-500" />;
      case 'completed':
        return <CheckCircle className="w-4 h-4 text-green-500" />;
      case 'failed':
      case 'timeout':
        return <AlertCircle className="w-4 h-4 text-red-500" />;
      default:
        return <Loader2 className="w-4 h-4 text-muted-foreground" />;
    }
  };

  const getStatusVariant = () => {
    switch (job.status) {
      case 'running':
        return 'default';
      case 'completed':
        return 'default';
      case 'failed':
      case 'timeout':
        return 'destructive';
      default:
        return 'secondary';
    }
  };

  const getCardClassName = () => {
    switch (job.status) {
      case 'running':
        return 'border-blue-200 bg-blue-50/50';
      case 'completed':
        return 'border-green-200 bg-green-50/50';
      case 'failed':
      case 'timeout':
        return 'border-red-200 bg-red-50/50';
      default:
        return 'border-muted bg-muted/20';
    }
  };

  const handleCancel = () => {
    cancelJob(job.id);
    onCancel?.();
  };

  const handleViewSuggestions = () => {
    openChatPanelPrompt(
      `Show me the ${job.results?.suggestions_generated || ''} suggestions generated by the ${job.job_type.replace('_', ' ')} job and help me decide which action to take first.`,
      { source: 'admin_job', jobId: job.id, jobType: job.job_type }
    );
  };

  const handleRetry = () => {
    void retryJob(job.id);
  };

  return (
    <Card className={`${getCardClassName()} transition-colors duration-200`}>
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            {getStatusIcon()}
            <span className="font-medium">
              {job.job_type.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}
            </span>
          </div>
          <Badge variant={getStatusVariant()}>
            {job.status}
          </Badge>
        </div>
      </CardHeader>
      
      <CardContent>
        <div className="space-y-3">
          {/* Progress Section */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span>Progress</span>
              <span className="font-medium">{job.progress_percentage}%</span>
            </div>
            <Progress value={job.progress_percentage} className="h-2" />
          </div>

          {/* Current Stage */}
          {job.current_stage && (
            <div className="text-sm text-muted-foreground">
              <span className="font-medium">Current stage:</span> {job.current_stage}
            </div>
          )}

          {/* ETA */}
          {job.estimated_completion && job.status === 'running' && (
            <div className="text-xs text-muted-foreground">
              <span className="font-medium">ETA:</span> {formatRelativeTime(new Date(job.estimated_completion))}
            </div>
          )}

          {/* Completed Results */}
          {job.status === 'completed' && job.results && Object.keys(job.results).length > 0 && (
            <div className="p-2 bg-white/60 rounded-md border">
              <div className="text-sm font-medium text-green-800 mb-1">Results</div>
              <div className="text-xs space-y-1">
                {job.results.suggestions_generated && (
                  <div>Generated {job.results.suggestions_generated} suggestions</div>
                )}
                {job.results.data_quality_score && (
                  <div>Data quality: {job.results.data_quality_score}%</div>
                )}
                {job.results.pipeline_health_score && (
                  <div>Pipeline health: {job.results.pipeline_health_score}%</div>
                )}
                {job.results.scan_duration_ms && (
                  <div>Completed in {Math.round(job.results.scan_duration_ms / 1000)}s</div>
                )}
              </div>
            </div>
          )}

          {/* Error Details */}
          {(job.status === 'failed' || job.status === 'timeout') && job.error_details && (
            <div className="p-2 bg-red-50 rounded-md border border-red-200">
              <div className="text-sm font-medium text-red-800 mb-1">Error</div>
              <div className="text-xs text-red-700">
                {job.error_details.error_message || 'An error occurred'}
                {job.error_details.stage_failed && (
                  <div className="mt-1">Failed during: {job.error_details.stage_failed}</div>
                )}
              </div>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex gap-2 pt-2">
            {job.status === 'running' && (
              <Button size="sm" variant="outline" onClick={handleCancel}>
                <X className="w-3 h-3 mr-1" />
                Cancel
              </Button>
            )}
            
            {onViewDetails && (
              <Button size="sm" variant="ghost" onClick={onViewDetails}>
                View Details
              </Button>
            )}

            {job.status === 'completed' && job.results?.suggestions_generated && (
              <Button size="sm" variant="default" onClick={handleViewSuggestions}>
                View Suggestions
              </Button>
            )}

            {(job.status === 'failed' || job.status === 'timeout') && job.retry_count < job.max_retries && (
              <Button size="sm" variant="outline" onClick={handleRetry}>
                Retry
              </Button>
            )}
          </div>

          {/* Meta Information */}
          <div className="text-xs text-muted-foreground pt-2 border-t">
            Started: {new Date(job.created_at).toLocaleTimeString()}
            {job.retry_count > 0 && (
              <span className="ml-2">• Attempt {job.retry_count + 1}</span>
            )}
            {job.priority > 1 && (
              <span className="ml-2">• High Priority</span>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
