// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { getSupabaseConfig } from '@/lib/secureConfig';

// Get configuration securely from environment
const { url, anonKey } = getSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(url, anonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'koffey-app'
    }
  }
});
